export const DRIZZLE_DB = 'DRIZZLE_DB';
export const QUOTATION_REPOSITORY = 'QUOTATION_REPOSITORY';
export const APPOINTMENT_REPOSITORY = 'APPOINTMENT_REPOSITORY';
export const WALLET_REPOSITORY = 'WALLET_REPOSITORY';
export const PAYMENT_REPOSITORY = 'PAYMENT_REPOSITORY';

